services:
  postgres:
    image: postgres:15
    container_name: typ
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: typedata
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/postgres_data:/var/lib/postgresql/data                                        │
volumes:
  pgvector-data:
