services:
  postgres:
    image: postgres:latest
    container_name: typ
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: typedata
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
volumes:
  pgvector-data:
