export const CGrammar = `
  program: (include+) function^;
  include: '#include <' header '>\n';
  header: 'stdio.h' | 'stdlib.h' | 'string.h' | 'math.h';
  function: functionheader ' {\n' functioncontent '}';
  functionheader: datatype ' ' identifier '(' paramlist ')';
  paramlist: (param ', ')* param | '';
  param: datatype ' ' identifier;
  functioncontent: block+;
  block: (statement+) | ifblock | whileblock | forblock | dowhileblock;
  ifblock: '    if (' conditionalexpression ') {\n' statement+ '    }\n';
  ifelseblock: '    if (' conditionalexpression ') {\n' statement+ '    } else {\n' statement+ '    }\n';
  whileblock: '    while (' conditionalexpression ') {\n' statement+ '    }\n';
  dowhileblock: '    do {\n' statement+ '    } while (' conditionalexpression ');\n';
  forblock: '    for (' datatype ' ' identifier ' = 0; ' identifier ' < ' operand '; ' identifier '++) {\n' statement+ '    }\n';
  conditionalexpression: conditionalexpone (conditionaljoin conditionalexpone)*;
  conditionalexpone: identifier conditionaloperation operand;
  conditionaloperation: ' < ' | ' > ' | ' == ' | ' != ' | ' <= ' | ' >= ';
  conditionaljoin: ' && ' | ' || ';
  statement: assignment | pointerassignment | arrayassignment | incrementstatement | decrementstatement;
  assignment: '        ' datatype ' ' identifier ' = ' expression ';\n';
  pointerassignment: '        ' datatype '* ' identifier ' = &' identifier ';\n';
  arrayassignment: '        ' datatype ' ' identifier '[' digit '] = {' arrayinit '};\n';
  arrayinit: (digit ', ')* digit;
  incrementstatement: '        ' identifier '++;\n';
  decrementstatement: '        ' identifier '--;\n';
  expression: operand (operator (operand | '(' expression ')'))*;
  operand: identifier | digit;
  operator: ' + ' | ' - ' | ' * ' | ' / ' | ' % ' | ' & ' | ' | ';
  datatype: 'int' | 'float' | 'double' | 'char' | 'long' | 'unsigned int';
  identifier: [a-z];
  digit: [0-9];
`;
