export const JavaGrammar = `
  program: class^;
  class: 'public class ' identifier ' {\n' function+ '}';
  function: functionheader ' {\n' functioncontent '    }\n';
  functionheader: '    public static ' datatype ' ' identifier '()';
  functioncontent: block+;
  block: (statement+) | ifblock | whileblock | forblock;
  ifblock: '        if (' conditionalexpression ') {\n' statement+ '        }\n';
  whileblock: '        while (' conditionalexpression ') {\n' statement+ '        }\n';
  forblock: '        for (int ' identifier ' = 0; ' identifier ' < ' operand '; ' identifier '++) {\n' statement+ '        }\n';
  conditionalexpression: conditionalexpone (conditionaljoin conditionalexpone)*;
  conditionalexpone: identifier conditionaloperation operand;
  conditionaloperation: ' < ' | ' > ' | ' == ' | ' != ';
  conditionaljoin: ' && ' | ' || ';
  statement: assignment | finalassignment;
  assignment: '        ' datatype ' ' identifier ' = ' expression ';\n';
  finalassignment: '        final ' datatype ' ' identifier ' = ' expression ';\n';
  expression: operand (operator (operand | '(' expression ')'))*;
  operand: identifier;
  operator: ' + ' | ' - ' | ' * ' | ' / ';
  datatype: 'int' | 'float' | 'double' | 'long';
  identifier: [a-z];
`;
